### ISSUE TITLE
Scroll sideways

### ISSUE THREAD

**Issue by David-Ro** [bettermtl/bettermtl.github.io#37] opened 2016-03-27 11:22 UTC
scrolling side to side: lets the present moment be in the center of a timeline, from which you scroll LEFT to see what just happened (pictures uploaded) and scroll RIGHT to see what's planned to happen next. Make each event box be square, and hang downwards from the box the various associated items: who, where, etc.

**Comment by pcuci** [comment] 2016-04-11 00:46
Duplicate of #42, closing

**Closed as completed** 2016-04-11 00:46 UTC
